# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 770f2efcad666b1d382acad63558affd2acf4a1a17aef8d845f68bbbaedef64c74dc0d10c77909e39811ac73ced512a7449997af97328051987e5911b841c41a

test:
  secret_key_base: fd5fc9f89eed2c93d358b0f50c3b3165b468a8a77e5fe061fcc5c4eb0c1f7ac00ba2d09bccb66904b268057dafa939a82ee39a859d12165d4b68971094b6efc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
